#!/usr/bin/env bash
# Regenerate the ledger index from the ledger itself. Never hand-edited.
# Usage: scripts/ledger-index.sh [--check]
#   (no args) rewrite INDEX.md
#   --check   exit 1 if INDEX.md differs from what this run would write
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LEDGER="$ROOT/harness/.agents/memory/recurring-failure-modes.md"
[[ -f "$LEDGER" ]] || LEDGER="$ROOT/.agents/memory/recurring-failure-modes.md"
[[ -f "$LEDGER" ]] || { echo "STOP: ledger not found"; exit 1; }
INDEX="$(dirname "$LEDGER")/INDEX.md"

# Surfaces a citation must appear in to count an entry LIVE.
CITE_DIRS=()
for d in "$ROOT/harness/.agents/roles" "$ROOT/harness/.agents/skills" \
         "$ROOT/harness/.claude/agents" "$ROOT/harness/.claude/skills" \
         "$ROOT/.agents/roles" "$ROOT/.agents/skills" \
         "$ROOT/.claude/agents" "$ROOT/.claude/skills"; do
  [[ -d "$d" ]] && CITE_DIRS+=("$d")
done
ORCH="$(dirname "$(dirname "$LEDGER")")/orchestrator.md"
[[ -f "$ORCH" ]] && CITE_DIRS+=("$ORCH")

cited_in() { # $1 = AST id -> comma-separated basenames, or empty
  [[ ${#CITE_DIRS[@]} -eq 0 ]] && return 0
  grep -rlF -- "$1" "${CITE_DIRS[@]}" 2>/dev/null \
    | sed "s|.*/\([^/]*\)/SKILL.md|\1|; s|.*/||" | sort -u | paste -sd, - || true
}

TMP="$(mktemp)"
{
  echo "# Ledger index"
  echo
  echo "Generated by \`scripts/ledger-index.sh\` — do not hand-edit; rerun it."
  echo
  echo "One line per entry, so the ledger can be browsed without reading it."
  echo "**Read the full entry only after this index names it** — the ledger is ~57k tokens."
  echo "\`grep -A40 '^### AST-0NN' recurring-failure-modes.md\` reads one entry."
  echo
  echo "**Cited by** names the live contracts and skills carrying the rule. An empty cell means"
  echo "no contract or skill points here: the entry was closed in code, went stale when 1.0.0"
  echo "rebuilt the method, or names a lesson nothing has bound yet. Which one is not derivable"
  echo "from this table — read the entry."
  echo
  echo "| ID | Lesson | Status | Words | Cited by |"
  echo "|---|---|---|---|---|"
} > "$TMP"

python3 - "$LEDGER" >> "$TMP" <<'PY'
import re,sys,subprocess,os
led=sys.argv[1]
t=open(led).read()
heads=list(re.finditer(r'(?m)^### (AST-\d+)\s*—\s*(.*)$', t))
bodies=re.split(r'(?m)^### AST-\d+.*$', t)[1:]
for h,b in zip(heads,bodies):
    aid, rest = h.group(1), h.group(2)
    m=re.search(r'·\s*([a-z]+)', rest)
    status=m.group(1) if m else '—'
    title=re.split(r'\s*·\s*[a-z]+', rest)[0].strip()
    if len(title)>96: title=title[:93].rstrip()+'…'
    title=title.replace('|','\\|')
    cited=subprocess.run(['bash','-c',f'echo "$CITED"'],capture_output=True,text=True)
    print(f"| `{aid}` | {title} | {status} | {len(b.split())} | @@{aid}@@ |")
PY

# fill the citation column
while IFS= read -r line; do
  if [[ "$line" =~ @@(AST-[0-9]+)@@ ]]; then
    id="${BASH_REMATCH[1]}"; c="$(cited_in "$id")"
    line="${line//@@${id}@@/${c:- }}"
  fi
  printf '%s\n' "$line"
done < "$TMP" > "$TMP.2"

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -q "$TMP.2" "$INDEX" >/dev/null 2>&1; then
    echo "STOP: INDEX.md is stale — run scripts/ledger-index.sh"; rm -f "$TMP" "$TMP.2"; exit 1
  fi
  echo "ok: INDEX.md current"; rm -f "$TMP" "$TMP.2"; exit 0
fi

mv "$TMP.2" "$INDEX"; rm -f "$TMP"
echo "wrote $INDEX ($(grep -c '^| \`AST-' "$INDEX") entries)"
